# Generated by Django 5.1.5 on 2025-04-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
    ]
