# Generated by Django 5.1.5 on 2025-03-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
