# Generated by Django 5.1.5 on 2025-03-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminderApp', '0002_reminder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
