# Generated by Django 5.1.5 on 2025-04-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminderApp', '0003_reminder_is_read_reminder_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='updated_at',
        ),
    ]
