# Generated by Django 5.1.5 on 2025-04-13 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'صیانہ و قائیہ'), ('B', 'صیانہ متوسطہ'), ('C', 'صیانہ شاملہ 1'), ('D', 'صیانہ شاملہ 2')], max_length=1)),
                ('kilometer', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('R', 'Replace'), ('I', 'Inspect'), ('A', 'Adjust'), ('C', 'Clean'), ('T', 'Tight'), ('L', 'Lubricate')], max_length=1, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='vehicleApp.maintenancetype')),
            ],
        ),
        migrations.CreateModel(
            name='SubInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='vehicleApp.inspectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='vehicleApp.inspectionitem')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='vehicleApp.maintenancetype')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='vehicleApp.servicetype')),
                ('sub_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='vehicleApp.subinspectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('near_expiry_notified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_at_service', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicleApp.inspectionitem')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicleApp.maintenancetype')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicleApp.servicetype')),
                ('sub_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicleApp.subinspectionitem')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleApp.vehicle')),
            ],
        ),
    ]
