# Generated by Django 5.1.5 on 2025-04-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceTask',
        ),
    ]
