# Generated by Django 5.1.5 on 2025-03-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
