# Generated by Django 5.1.5 on 2025-03-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0002_vehicleservicerecord_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='expiry_date',
            field=models.DateField(default='2025-03-25'),
            preserve_default=False,
        ),
    ]
