from django.db import migrations
from datetime import date

def insert_vehicle_data(apps, schema_editor):
    Vehicle = apps.get_model('vehicleApp', 'Vehicle')


    vehicles = [
             {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د ك ر 1537',
            'model': '2020',
            'manufacturer': 'شيفورلية',
            'purchase_date': date(2019, 12, 9),
            'expiry_date': date(2023, 9, 2),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د ك ر 1613',
            'model': '2020',
            'manufacturer': 'شيفورلية',
            'purchase_date': date(2019, 12, 9),
            'expiry_date': date(2023, 9, 2),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د م ه 8515',
            'model': '2020',
            'manufacturer': 'نيسان',
            'purchase_date': date(2020, 9, 3),
            'expiry_date': date(2024, 1, 23),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د م ه 8615',
            'model': '2020',
            'manufacturer': 'نيسان',
            'purchase_date': date(2020, 9, 3),
            'expiry_date': date(2024, 1, 23),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د ك ر 1603',
            'model': '2020',
            'manufacturer': 'شيفورلية',
            'purchase_date': date(2019, 12, 9),
            'expiry_date': date(2023, 9, 2),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3470',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 10, 29),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3488',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 3, 8),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3462',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 6, 10),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3473',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 2, 17),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3494',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 18),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3519',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 22),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3539',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 11, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3456',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 30),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3482',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 28),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3484',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 7),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3500',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 6),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3522',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 29),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3530',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 11),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3463',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 12, 23),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3469',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2024, 12, 3),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3475',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 12, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3479',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 19),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3487',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 28),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3491',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 11, 28),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3493',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 12, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3495',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 2, 13),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3498',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 10, 5),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3501',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 5),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3518',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 23),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3523',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 4, 10),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3526',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 12),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3527',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 6, 24),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3531',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 25),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3532',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 16),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3533',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 6),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3537',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 25),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3541',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 1, 31),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3497',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 1, 2),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3505',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2024, 6, 12),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3510',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 7, 11),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3453',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 3, 24),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3459',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2024, 11, 26),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3460',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 8),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3466',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 7),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3472',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 12, 2),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3489',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2024, 12, 29),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3490',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 3, 22),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3508',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 8),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3521',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 9, 1),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3536',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 3, 3),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3540',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 3, 1),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3455',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 5, 5),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3486',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 1, 23),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3509',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 7, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3513',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 2, 24),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3515',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 1, 12),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3517',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 7, 8),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3520',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 13),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3528',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 22),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3529',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 5, 25),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3538',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 30),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3457',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 8, 24),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3480',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 5, 16),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3485',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2024, 12, 23),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3496',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2024, 11, 29),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3502',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 12, 8),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3516',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 11),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3524',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 7, 7),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3454',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 10, 14),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3458',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 3, 13),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3468',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 20),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3477',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3534',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 3, 17),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3467',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 23),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3471',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 20),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3492',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 2, 20),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3504',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3506',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 2, 11),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3461',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 28),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3464',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 1, 3),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3465',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 22),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3474',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 4, 22),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3476',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 13),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3478',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 12, 26),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3481',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 1),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3499',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 2, 8),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3503',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2026, 1, 28),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3511',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 6, 3),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'د و ن 3512',
            'model': '2021',
            'manufacturer': 'كيا',
            'purchase_date': date(2021, 7, 15),
            'expiry_date': date(2025, 11, 27),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7641',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8763',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8784',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8796',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8779',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8798',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8862',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7649',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8775',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8861',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8874',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8927',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7631',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8780',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8786',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8864',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8869',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي8795',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8782',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8790',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8872',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7634',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7637',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7640',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7648',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8791',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8792',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8793',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8797',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8799',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8863',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8870',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8876',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8928',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7638',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7639',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7642',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7647',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8783',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8785',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8789',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8865',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8875',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7632',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ك 7643',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8781',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8867',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ر ي 8873',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 3, 19),
            'expiry_date': date(2026, 2, 15),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2563',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2564',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2576',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2585',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2590',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2595',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2596',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2601',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2603',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2612',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2613',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2573',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2579',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2597',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2561',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2572',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2589',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2592',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2599',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2568',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2567',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2582',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2574',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2577',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2578',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2581',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2588',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2591',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2593',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2598',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2602',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2606',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2607',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2608',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2583',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2586',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2605',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2609',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2571',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2584',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2604',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2566',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2575',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2580',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2587',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2594',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2562',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2565',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2569',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2570',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2610',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر س ع 2611',
            'model': '2023',
            'manufacturer': 'نيسان',
            'purchase_date': date(2023, 4, 6),
            'expiry_date': date(2026, 3, 4),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6383',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6397',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6399',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6393',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6396',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6421',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6424',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6398',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6416',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ص 9257',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6380',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6391',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6402',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6407',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6413',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6389',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6405',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6406',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6415',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6417',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6382',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6385',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6386',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6394',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6395',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6401',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6408',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6409',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6411',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6418',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6419',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6420',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6422',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6423',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6388',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6392',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6412',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6384',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6403',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6410',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6381',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6387',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6390',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6404',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر م ع 6414',
            'model': '2024',
            'manufacturer': 'كيا',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3305',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3309',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3312',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3342',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3310',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3318',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3321',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3354',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3360',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3307',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3347',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3359',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3298',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3315',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3316',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3317',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3319',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3320',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3324',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3326',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3328',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3340',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3345',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3348',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3349',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3350',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3351',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3352',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3357',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3361',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3299',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3356',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3325',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن م 3675',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3302',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3308',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3301',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3304',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3306',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3314',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3327',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3329',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3341',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3346',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },
        {
            'company_id': 1,
            'user_id': 1,
            'registration_number': 'ر ن ع 3358',
            'model': '2024',
            'manufacturer': 'نيسان',
            'purchase_date': date(2024, 11, 11),
            'expiry_date': date(2027, 10, 9),
            'near_expiry_notified': True,
        },



    ]

    for data in vehicles:
        Vehicle.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0002_delete_maintenancetask'),
    ]

    operations = [
        migrations.RunPython(insert_vehicle_data),
    ]
