# Generated by Django 5.1.5 on 2025-03-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0003_vehicle_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='near_expiry_notified',
            field=models.BooleanField(default=False),
        ),
    ]
