# Generated by Django 5.1.5 on 2025-04-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0004_vehicle_near_expiry_notified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceCategory',
            new_name='MaintenanceType',
        ),
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='category',
            new_name='maintenance_type',
        ),
        migrations.RenameField(
            model_name='vehicleservicerecord',
            old_name='maintenance_category',
            new_name='maintenance_type',
        ),
    ]
