# Generated by Django 5.1.5 on 2025-04-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0005_rename_maintenancecategory_maintenancetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
    ]
