# Generated by Django 5.1.5 on 2025-04-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0006_remove_vehicle_created_at_remove_vehicle_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='code',
            field=models.CharField(choices=[('R', 'Replace'), ('I', 'Inspect'), ('A', 'Adjust'), ('C', 'Clean'), ('T', 'Tight'), ('L', 'Lubricate')], max_length=1, unique=True),
        ),
    ]
